<a href="https://colab.research.google.com/github/tolibovdilshodbek/week1lab/blob/main/exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals Exercises

This notebook contains exercises based on the PyTorch Fundamentals tutorial. Each section corresponds to a topic from the original notebook. Complete the exercises by filling in the code cells where indicated.

## 1. Introduction to Tensors

### Exercise 1.1: Create a scalar tensor
Create a scalar tensor with the value 42 and print its value, number of dimensions (ndim), and shape.

In [1]:
import torch

# TODO: Create a scalar tensor
scalar = torch.tensor(42)

# Print details
print(scalar)
print(f"Number of dimensions: {scalar.ndim}")
print(f"Shape: {scalar.shape}")

tensor(42)
Number of dimensions: 0
Shape: torch.Size([])


### Exercise 1.2: Create a vector tensor
Create a vector tensor with values [1, 2, 3, 4] and print its value, ndim, and shape.

In [2]:
# TODO: Create a vector tensor
vector = torch.tensor([1, 2, 3, 4])

# Print details
print(vector)
print(f"Number of dimensions: {vector.ndim}")
print(f"Shape: {vector.shape}")

tensor([1, 2, 3, 4])
Number of dimensions: 1
Shape: torch.Size([4])


### Exercise 1.3: Create a matrix tensor
Create a 2x3 matrix tensor with values [[1, 2, 3], [4, 5, 6]] and print its details.

In [3]:
# TODO: Create a matrix tensor
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])

# Print details
print(matrix)
print(f"Number of dimensions: {matrix.ndim}")
print(f"Shape: {matrix.shape}")

tensor([[1, 2, 3],
        [4, 5, 6]])
Number of dimensions: 2
Shape: torch.Size([2, 3])


### Exercise 1.4: Create a 3D tensor
Create a tensor of shape (2, 2, 2) with sequential values from 1 to 8 using torch.arange and reshape.

In [10]:
# TODO: Create a 3D tensor
tensor_3d =  torch.arange(1, 9).reshape(2, 2, 2)

# Print details
print(tensor_3d)
print(f"Number of dimensions: {tensor_3d.ndim}")
print(f"Shape: {tensor_3d.shape}")

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Number of dimensions: 3
Shape: torch.Size([2, 2, 2])


## 2. Random Tensors

### Exercise 2.1: Create a random tensor
Create a random tensor of shape (4, 4) and print it along with its dtype.

In [11]:
# TODO: Create random tensor
random_tensor = torch.rand(size=(4, 4))

print(random_tensor)
print(f"Datatype: {random_tensor.dtype}")

tensor([[0.2160, 0.6631, 0.8803, 0.0011],
        [0.3753, 0.9213, 0.2583, 0.8323],
        [0.0698, 0.5626, 0.6108, 0.9572],
        [0.2225, 0.5166, 0.0072, 0.3619]])
Datatype: torch.float32


### Exercise 2.2: Create an image-sized random tensor
Create a random tensor of shape (3, 224, 224) simulating an image (channels, height, width).

In [12]:
# TODO: Create image-sized random tensor
image_tensor = torch.rand(size=(3, 224, 224))

print(f"Shape: {image_tensor.shape}")

Shape: torch.Size([3, 224, 224])


## 3. Zeros and Ones

### Exercise 3.1: Create a tensor of zeros
Create a tensor of zeros with shape (5, 5).

In [16]:
# TODO: Create zeros tensor
zeros = torch.zeros(size=(5, 5))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]),
 torch.float32)

### Exercise 3.2: Create a tensor of ones like another tensor
Create a random tensor of shape (3, 3), then create a tensor of ones with the same shape using ones_like.

In [22]:
random_tensor = torch.rand(3, 3)
# TODO: Create ones like
random_tensor = torch.rand(3, 3)
ones_like = torch.ones_like(random_tensor)
ones_like, ones_like.dtype


(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 torch.float32)

## 4. Creating Ranges

### Exercise 4.1: Create a range tensor
Create a tensor with values from 0 to 20 with a step of 2 using torch.arange.

In [23]:
# TODO: Create range tensor
range_tensor = torch.arange(start=0, end=20, step=2)
range_tensor

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## 5. Tensor Datatypes

### Exercise 5.1: Create tensors with specific dtypes
Create a tensor with values [1.0, 2.0, 3.0] using dtype=torch.float16 and another with dtype=torch.int64.

In [29]:
# TODO: float16 tensor
float16_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)

# TODO: int64 tensor
int64_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.int64)

float16_tensor
int64_tensor


tensor([1, 2, 3])

### Exercise 5.2: Change dtype
Convert the float16_tensor to float32.

In [40]:
# TODO: Change dtype
float32_tensor = float16_tensor.type(torch.float32)
float32_tensor


tensor([1., 2., 3.])

## 6. Getting Information from Tensors

### Exercise 6.1: Print tensor info
Create a random tensor of shape (2, 3, 4) and print its shape, dtype, and device.

In [45]:
# TODO: Create tensor and print info
info_tensor = torch.rand(2,3,4)
info_tensor


tensor([[[0.6783, 0.7798, 0.6661, 0.1334],
         [0.2634, 0.9255, 0.5395, 0.6376],
         [0.1010, 0.2697, 0.5500, 0.6821]],

        [[0.9104, 0.0325, 0.0507, 0.2720],
         [0.3896, 0.3092, 0.7397, 0.9313],
         [0.8299, 0.9055, 0.6839, 0.0504]]])

## 7. Manipulating Tensors (Basic Operations)

### Exercise 7.1: Perform basic operations
Create a tensor [10, 20, 30]. Add 5, subtract 10, multiply by 2, and divide by 10.

In [46]:
tensor = torch.tensor([10, 20, 30])
# TODO: Add 5
tensor + 5
# TODO: Subtract 10
tensor - 10
# TODO: Multiply by 2
tensor * 2
# TODO: Divide by 10
tensor / 10

tensor([1., 2., 3.])

### Exercise 7.2: Matrix multiplication
Create two tensors A (2x3) and B (3x2) with random values and perform matrix multiplication.

In [56]:
# TODO: Create A and B
A = torch.rand(2,3)
B = torch.rand(3,2)

# TODO: Matrix mul using torch.mm
result_mm = torch.mm(A,B)

# TODO: Matrix mul using @
result_at = A @ B

A.shape
B.shape
result_mm.shape
result_at.shape


torch.Size([2, 2])

## 8. Tensor Aggregation

### Exercise 8.1: Find min, max, mean, sum
Create a tensor with values from 0 to 100 and find its min, max, mean, and sum.

In [62]:
agg_tensor = torch.arange(0, 101)
# TODO: Min
min_val = torch.min(agg_tensor)

# TODO: Max
max_val = torch.max(agg_tensor)

# TODO: Mean (note: may need to cast to float)
mean_val = torch.max(agg_tensor)

# TODO: Sum
sum_val = torch.sum(agg_tensor)

print(min_val)
print(max_val)
print(mean_val)
print(sum_val)

tensor(0)
tensor(100)
tensor(100)
tensor(5050)


### Exercise 8.2: Argmin and argmax
Find the positions of the minimum and maximum values in the above tensor.

In [63]:
# TODO: Argmin
print(agg_tensor.argmin())
# TODO: Argmax
print(agg_tensor.argmax())

tensor(0)
tensor(100)


## 9. Reshaping, Stacking, Squeezing, Unsqueezing

### Exercise 9.1: Reshape a tensor
Create a tensor of shape (10,) and reshape it to (2, 5).

In [66]:
reshape_tensor = torch.arange(10)
# TODO: Reshape
reshaped = reshape_tensor.reshape(2, 5)
print(reshaped)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


### Exercise 9.2: Stack tensors
Create two tensors of shape (2, 2) and stack them vertically and horizontally.

In [70]:
tensor1 = torch.rand(2, 2)
tensor2 = torch.rand(2, 2)
# TODO: Stack vertically (dim=0)
print(torch.stack((tensor1, tensor2), dim=0))
# TODO: Stack horizontally (dim=1)
print(torch.stack((tensor1, tensor2), dim=1))

tensor([[[0.3331, 0.9672],
         [0.8463, 0.0206]],

        [[0.5702, 0.2655],
         [0.9082, 0.8871]]])
tensor([[[0.3331, 0.9672],
         [0.5702, 0.2655]],

        [[0.8463, 0.0206],
         [0.9082, 0.8871]]])


### Exercise 9.3: Squeeze and unsqueeze
Create a tensor of shape (1, 3, 1), squeeze it, then unsqueeze it back on dim=0.

In [73]:
squeeze_tensor = torch.rand(1, 3, 1)
# TODO: Squeeze
squeezed = torch.squeeze(squeeze_tensor)

# TODO: Unsqueeze on dim=0
unsqueezed = torch.unsqueeze(squeezed, dim=0)
print(squeezed)
print(unsqueezed)

tensor([0.5327, 0.8839, 0.9467])
tensor([[0.5327, 0.8839, 0.9467]])


### Exercise 9.4: Permute
Create an image tensor (3, 100, 100) and permute it to (100, 100, 3).

In [75]:
image_tensor = torch.rand(3, 100, 100)
# TODO: Permute
image_tensor = torch.randn(3, 100, 100)
print(image_tensor.shape)

torch.Size([3, 100, 100])


## 10. Indexing

### Exercise 10.1: Index into a tensor
Create a tensor [[[1,2,3],[4,5,6],[7,8,9]]] and index to get 5, then the entire second row.

In [76]:
index_tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
# TODO: Get 5
import torch

tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

# TODO: Get second row [4,5,6]
second_row = tensor[0, 1, :]
print(second_row)


tensor([4, 5, 6])


## 11. PyTorch and NumPy

### Exercise 11.1: NumPy to PyTorch
Create a NumPy array [1,2,3,4] and convert it to a PyTorch tensor.

In [77]:
import numpy as np
import torch

# Step 1: Create NumPy array
np_array = np.array([1, 2, 3, 4])

# Step 2: Convert to PyTorch tensor
tensor = torch.from_numpy(np_array)

print(tensor)
print(tensor.dtype)


tensor([1, 2, 3, 4])
torch.int64


### Exercise 11.2: PyTorch to NumPy
Create a PyTorch tensor [5,6,7,8] and convert it to a NumPy array.

In [ ]:
pytorch_tensor = torch.tensor([5,6,7,8])
# TODO: Convert to NumPy
to_numpy =

## 12. Reproducibility

### Exercise 12.1: Set manual seed
Set the manual seed to 77 and create two random tensors of shape (2,2). Check if they are equal.

In [79]:
import torch

torch.manual_seed(77)
tensor1 = torch.rand(2, 2)
tensor2 = torch.rand(2, 2)

are_equal = torch.equal(tensor1, tensor2)
print("Tensor 1:\n", tensor1)
print("Tensor 2:\n", tensor2)
print("Are they equal?", are_equal)


Tensor 1:
 tensor([[0.2919, 0.2857],
        [0.4021, 0.4645]])
Tensor 2:
 tensor([[0.9503, 0.2564],
        [0.6645, 0.8609]])
Are they equal? False


## 13. Running on GPUs

### Exercise 13.1: Check for GPU
Write code to check if CUDA is available and set the device accordingly.

In [81]:
import torch

# Check if CUDA (GPU) is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Selected device:", device)
tensor = torch.tensor([1, 2, 3], device=device)
print(tensor)
print(tensor.device)





Selected device: cpu
tensor([1, 2, 3])
cpu


### Exercise 13.2: Move tensor to GPU
Create a tensor and move it to the GPU if available. Then move it back to CPU and convert to NumPy.

In [82]:
import torch

# Step 1: Check device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# Step 2: Create a tensor
tensor = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32)

# Step 3: Move tensor to GPU (if available)
tensor_gpu = tensor.to(device)
print("Tensor on device:", tensor_gpu)
print("Device:", tensor_gpu.device)

# Step 4: Move tensor back to CPU
tensor_cpu = tensor_gpu.to("cpu")
print("Tensor back on CPU:", tensor_cpu)
print("Device:", tensor_cpu.device)

# Step 5: Convert to NumPy
tensor_np = tensor_cpu.numpy()
print("NumPy array:", tensor_np)
print("Type:", type(tensor_np))


Using device: cpu
Tensor on device: tensor([1., 2., 3., 4., 5.])
Device: cpu
Tensor back on CPU: tensor([1., 2., 3., 4., 5.])
Device: cpu
NumPy array: [1. 2. 3. 4. 5.]
Type: <class 'numpy.ndarray'>
